#!/bin/sh

c=$(printf "no\nstay the same\nyes" | dmenu -i -p "Flash?")

[ "$c" = "yes" ] && offlater=y && $PHONE flash on
[ "$c" = "no" ] && $PHONE flash off

dev=$(ls /dev/video* | dmenu -i -p "Cameras:")

echo "$dev" > $HOME/.local/camera
mpv --profile=low-latency -- $dev

[ "$offlater" = "y" ] && $PHONE flash off 
