#!/bin/sh

get_cal() {
	calcurse -D $HOME/.config/calcurse $1 | awk "/$2/" | wc -l
}
todo=$(get_cal -t)
if [ "$todo" = "0" ]
then
	todo=$todo
else
	todo=$(($todo-1))
fi
echo "[CAL A:$(get_cal -a "*")/T:$todo]"
