#!/bin/sh

tempt=$(acpi -t | awk '{s+=$4} END {print s}')
tempc=$(acpi -t | wc -l)
temp=$(($tempt/$tempc))
temp="$temp"
[ $temp -gt 65 ] && temp="^c#aa0000^$temp"
[ $temp -lt 65 ] && temp="^c#aaaa00^$temp"
[ $temp -lt 55 ] && temp="^c#00aa00^$temp"

cpu=$(
	(
		cat /proc/stat
		sleep 1
		cat /proc/stat
	) | awk '
	BEGIN {
		pass = 0;
		height = 10; # pixels
	}

	/intr/ { pass = 1; }

	/^cpu[0-9][0-9]*/ && !pass {
		sub(/cpu/, "", $1);
		total = 0;
		for (i = 2; i <= NF; i++)
			total = total + $i;
		ctotal[$1] = total;
		cidle[$1] = $5;
	}

	/^cpu[0-9][0-9]*/ && pass {
		sub(/cpu/, "", $1);
		total = 0;
		for (i = 2; i <= NF; i++)
			total += $i;
		diff = total - ctotal[$1];
		idle = $5    - cidle[$1];
		used = diff  - idle;
		decimal = used / diff;
		barheight = decimal * height;

		if (decimal > 0.8)
			col = "^c#aa0000^";
		else if (decimal > 0.5)
			col = "^c#aa7700^";
		else
			col = "^c#00aa00^";

		printf("^c#000000^^r0,2,5,1^^r0,3,1,%d^^f1^%s^r0,%d,3,%d^^c#000000^^r0,12,3,1^^f3^^r0,3,1,%d^^f2^", 
			height,
			col, (height - barheight + 3), barheight,
			height);
	}'
)

echo "[^f1^$cpu^d^${temp}C]"
