#!/bin/bash
#
# i3blocks/cpu
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

cpup=$(ps -e -o %cpu | awk '{s+=$1} END {print s}' | sed 's/\..*$//g')
cpuc=$(lscpu | awk '/^CPU\(s\):/{print $2}')
cpu=$(($cpup/$cpuc))
tempt=$(acpi -t | awk '{s+=$4} END {print s}')
tempc=$(acpi -t | wc -l)
temp=$(($tempt/$tempc))
temp=" $temp"
[ $temp -gt 60 ] && [ ! $temp -gt 70 ] && temp=" ^c#ffff00^^b#888800^$temp"
[ $temp -gt 70 ] && temp=" ^c#ff0000^^b#770000^$temp"
[ $temp -lt 40 ] && temp=" ^c#7777dd^^b#222277^$temp"
echo "[C $cpu%${temp}C]"
echo
echo \#7525C8
