#!/bin/bash

mkdir -p /tmp/blocks
block(){
	$HOME/.scripts/dwmblocks/$1 > /tmp/blocks/$1 &
}

block host
block vol
fetchmail &
while true
do
	block bat
	block cpu
	block mem
	sleep 3
done &

while true
do
	block mpv
	block time
	block time2
	sleep 1
done &

while true
do
	# block net
	block news
	block disk
	block disk2
	block mail
	block rem
	sleep 20
done &

mkdir /tmp/dwmblocks
cd /tmp/dwmblocks
while true
do
	sleep 0.1
	for f in /tmp/blocks/*
	do
		grep '[[:alnum:]]' < $f >/dev/null && cp $f /tmp/dwmblocks
	done
	xsetroot -name "$(for void in $(seq 150); do printf "  "; done) $(cat mpv bat cpu mem disk disk2 news mail rem time vol time2 host | sed '/^#/d;/^$/d' | sed '1~2s/^/\^c#ffaaaa\^/;2~2s/^/\^c#aaaaff\^/;s~\[~ ^b#1a3136^ ~g;s~\]~ ^d^~g' | tr '\n' ' ')    "
done &
