#!/bin/bash

mkdir -p ~/.cache/blocks
block(){
	$HOME/.scripts/dwmblocks/$1 > $HOME/.cache/blocks/$1 &
}

block host
fetchmail &
while true
do
	block bat
	block cpu
	block mem
	block vol
	sleep 3
done &

while true
do
	block mpv
	block time
	sleep 1
done &

while true
do
	block net
	block news
	block weather
	block disk
	block disk2
	block time2
	sleep 20
done &

cd ~/.cache/blocks
while true
do
	sleep 1
	xsetroot -name "$(for void in $(seq 150); do printf " "; done) $(cat bat cpu disk disk2 mem mpv net news vol weather time time2 host | sed '/^#/d;/^$/d' | sed '1~2s/^/\^c#aaaaff\^/;2~2s/^/\^c#ffaaaa\^/;s~\[~ ^b#1a3136^ ~g;s~\]~ ^d^~g' | tr '\n' ' ')    "
done
