#!/bin/sh

cd $(dirname $0)

mkdir -p /tmp/blocks
block(){
	$HOME/.scripts/dwmblocks/$1 > /tmp/blocks/$1 &
}

block vol
fetchmail &
while true
do
	block bat
	block cpu
	block mem
	sleep 3
done &

while true
do
	block time2
	sleep 1
done &

while true
do
	block news
	block mail
	block rem
	block torrent
	sleep 20
done &

while true
do
	block time
	block net
	sleep 900
done &

mkdir /tmp/dwmblocks
cd /tmp/dwmblocks
while true
do
	sleep 0.1
	for f in /tmp/blocks/*
	do
		grep '[[:alnum:]]' < $f >/dev/null && cp $f /tmp/dwmblocks
	done
	xsetroot -name " $(cat bat net torrent cpu mem vol time time2 2>/dev/null | sed 's~\[~ ^b#1a3136^ ~g;s~\]~ ^d^~g' | tr '\n' ' ')"
done
