#!/bin/sh
# Copyright (c) 2019-2021 Hayden Hamilton.

[ "$(uname)" = "Linux" ] && {
	mem=$(free -h | awk '{print $3 "/" $2}' | head -n 2 | tail -n 1)
	echo "$mem" | grep 'Mi/' >/dev/null && col="^c#00aa00^"
	echo "$mem" | grep '1\.[0-4]Gi/' >/dev/null && col="^c#aaaa00^"
	echo "$mem" | grep '1\.[5-9]Gi/' >/dev/null && col="^c#aa7700^"
	echo "$mem" | grep '2\..Gi/' >/dev/null && col="^c#aa0000^"
}
[ "$(uname)" = "OpenBSD" ] && {
	total=$(dmesg | grep "^real mem" | awk '{print $5}' | tr -d 'MB()')
	avail=$(dmesg | grep "^avail mem" | awk '{print $5}' | tr -d 'MB()')
	used=$(echo "$total - $avail" | bc)
	mem="${used}M/${avail}M"
	[ $used -le 1000 ] && col="^c#00aa00^"
	[ $used -gt 1000 ] && col="^c#aaaa00^"
	[ $used -gt 1500 ] && col="^c#aa7700^"
	[ $used -gt 2000 ] && col="^c#aa0000^"
}
echo "[^c#7777cc^M^d^${col}${mem}]"
