#!/bin/bash
#
# dwmblocks/net
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

ip=$(curl -s http://n0a110w.xyz/ip.sh || echo "No network.")
ip=$(echo "$ip" | tail -n 1)
echo "[$ip]"
