#!/bin/sh
#
# dwmblocks/net
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

ip=$(curl -s http://icanhazip.com)
[ -z $ip ] && exit
ip=$(echo "$ip" | tail -n 1)
echo "[$ip]"
