#!/bin/bash
#
# dwmblocks/news
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

newsboat -x reload 2>/dev/null && {
	rss=$(newsboat -x print-unread | sed 's/ unread articles//g')
	rssbnb=$(srssbnbc -n)
	echo "[NWS $unread]"
	echo
	echo \#498364
}
