#!/bin/sh

echo $(curl wttr.in/?format=%D) > $HOME/.cache/wttrD
echo $(curl wttr.in/?format=%d) > $HOME/.cache/wttrd
echo $(curl wttr.in/?format=%S) > $HOME/.cache/wttrS
echo $(curl wttr.in/?format=%s) > $HOME/.cache/wttrs
echo $(curl wttr.in/?format=%C) > $HOME/.cache/wttrC

day=$(date +%A | tr '[:lower:]' '[:upper:]')
[ $(date +%u) -eq 6 ] || [ $(date +%u) -eq 7] && col="^c#007700^" || col="^c#888888^"

month=$(date +%m)
[ $month -ge 3 ] && [ $month -le 5 ] && col2="^c#aaaa00^" #spring
[ $month -ge 6 ] && [ $month -le 7 ] && col2="^c#00aa00^" # summer
[ $month -ge 8 ] && [ $month -le 11 ] && col2="^c#a61028^" # autumn
[ $month -eq 12 ] || [ $month -eq 1 ] || [ $month -eq 2 ] && col2="^c#cccccc^" # winter

printf "[%s%s%s%s]" "$col" "$day" "$col2" "$(date +%d/%m)"
