#!/bin/sh
# Copyright (c) 2019-2021 Hayden Hamilton.

[ "$(uname)" = "Linux" ] && {
	toggled=$(amixer sget Master | awk '/Mono/ {print $6}' | tr -d '[]\n')
	volume=$(amixer sget Master | awk '/Mono/ {print $4}' | tr -d '[]\n')
}
[ "$(uname)" = "OpenBSD" ] && {
	toggled=$(sndioctl output.mute | sed 's/.*=//;s/0/on/;s/1/off/' | tr -d '\n')
	volume=$(sndioctl output.level | sed -E 's/.*=//;s/(.)\.(..)(.)/\1\2.\3/;s/^0*//;s/\.0$//;s/$/%/' | tr -d '\n')
}

echo "$toggled" | grep on >/dev/null && {
icon="
              

          #   
 ####   # #  
#   # # # # 
#   #  # # #
#   #  # # #
#   #  # # #
#   # # # # 
 ####   # #  
          #"
} || {
icon="
              

             
 ####       
#   # #   # 
#   #  # #  
#   #   #   
#   #  # #  
#   # #   # 
 ####"
}

printf '%s' "["
printf '%s' "$icon" | awk '
	BEGIN { line = 0; }
	{
		split($0, chars, "");
		for (i=1; i <= length($0); i++)
			if (chars[i] == "#")
			printf("^r%d,%d,1,1^", i, line);
		line++;
	}'

printf '^f14^%s]\n' "$volume"
