#!/bin/sh
#
# dwmblocks/vol
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

toggled=$(amixer sget Master | awk '/Mono/ {print $6}' | tr -d '[]')
volume=$(amixer sget Master | awk '/Mono/ {print $4}' | tr -d '[]')
output="$(echo ${volume} | tr "\n" " ")$(echo "${toggled}" | grep 'on' >/dev/null && printf '^c#00cc00^' || printf '^c#cc0000^')$(echo ${toggled} | tr "\n" " " | sed 's/ //g')"
echo "[VOL $output]"
