#!/bin/sh
killprog(){
	for prog in $(printf "$@")
	do
		pkill $prog
	done
}

0x0(){
	for file in $(printf "$@")
	do
		name=$(curl -n -F "file=@$file" http://0x0.st)
		echo "$file has been hosted at $name"
		echo "$name" | xclip
	done
}

ix(){
	for file in $(printf "$@")
	do
		name=$(curl -n -F "f:1=<-" http://ix.io < $file)
		echo "$file has been hosted at $name"
		echo "$name" | xclip
	done
}

pc(){
	"$@" | curl -n -F "f:1=<-" http://ix.io
}

make(){
	[ -f make.sh ] && {
		sh make.sh "$@"
	} || {
		command make "$@"
	}
}

man(){
	command man -c "$@" | centre
}
