.Dd hhvn-scripts
.Dt rmpv-list 1
.Sh NAME
.Nm rmpv-list
.Nd manipulate
.Xr rmpv-list 5
files for use with
.Xr rmpv 1
.Sh SYNOPSIS
.Nm
.Fl c
.Ar directory
.Nm
.Fl m
.Ar list
.Ar file
.Ar weight
.Sh OPTIONS
.Fl c
\ \ create new list from scratch by finding all files in the
.Ar directory .
.Fl m
\ \ edit the weight of the given
.Ar file
in a given
.Ar list .
.Sh SEE ALSO
.Xr rmpv-list 5 ,
.Xr rmpv 1 ,
.Xr hhvn-scripts 7
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
