.Dd hhvn-obsd-compat
.Dt $PROGNAME 5
.Sh PROLOGUE
These scripts are barebone replicas of some GNU programs that I miss on openbsd

IMO, this is the lazy method of ensuring compatibility :)
.Sh NAME
.Nm $FORMNAME
.Nd $FORMDEF
.Sh DESCRIPTION
$FORMDESC

use: /$$FORM[^ ]* in vim
.Sh SEE ALSO
.Xr hhvn-scripts 7
.Xr hhvn-obsd-compat 7
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
