#!/bin/sh

xrandr --output LVDS1 --off --output VGA1 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --off --output DP1 --off --output HDMI2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP2 --off --output DP3 --off --output TV1 --off
