#!/bin/sh
# my monitors face the windows, so sometimes when it's bright I like to wear sunglasses.
# To do this I first double the gamma of my displays with this script.
# sun              = 1.0
# screen           = 2.0
# sun + sunglasses = 0.5
# screen + glasess = 1.0

pkill redshift
sleep 1
xrandr --output HDMI2 --brightness 2.0
xrandr --output VGA1  --brightness 2.0
