#!/bin/sh

case "$#" in
	1)
		last="$1"
		;;
	2)
		first="$1"
		last="$2"
		;;
	3)
		first="$1"
		incr="$2"
		last="$3"
		;;
	*)
		echo "usage: seq <last>"
		echo "       seq <first> <last>"
		echo "       seq <first> <incr> <last>"
		exit 1
		;;
esac


echo | awk -v "first=${first:-1}" -v "incr=${incr:-1}" -v "last=$last" '
	{
		for (i=first; i <= last; i=i+incr)
			print i
	}'
