#!/bin/sh

total=100
[ "$(uname)" = "Linux" ] && {
	case "$(acpi | awk '{print $3}' | tr -d ',')" in
		"Charging") charging=y ;;
		"Discharging") discharging=y ;;
	esac
	charge=$(acpi | awk '{print $NF}' | tr -d ',%')
}

[ "$(uname)" = "OpenBSD" ] && {
	case "$(apm | head -n 2 | tail -n 1 | sed 's/.*: //')" in
		"not"*) discharging=y ;;
		*) charging=y ;;
	esac
	charge=$(apm | head -n 1 | sed -E 's/%.*//;s/.*([0-9])/\1/')
}
num=$(echo "scale=2; ($charge/$total)*100" | bc | sed 's~\..*$~~')
[ "$charging" = "y" ] && ind="^c#00aa00^+"
[ $num -ge 98 ] && ind=""
[ "$discharging" = "y" ] && ind="^c#aa0000^-"

[ "$discharging" != "y" ] && [ $num -ge 50 ] && col="^c#00aa00^"
[ "$discharging" = "y" ] && [ $num -lt 20 ] && col="^c#aa0000^"

printf '[^c#7777cc^B%s%s%%%s]\n' "${col:-^c#aa7700^}" "$num" "$ind"
