.Dd 27 Apr 2021
.Dt hhvn-git 7
.Os hhvn-git(7)
.Sh Name
.Nm hhvn-git
.Nd set of git aliases and wrappers
.Sh FILES
$HOME/.config/git/*
.Sh COMPONENTS
.Bl -tag -compact -width 'git-xx(x)'
.It Xr git-hs 1
history
.It Xr git-fm 1
format-patch
.It Xr git-ac 1
add & commit
.It Xr git-re 1
remote
.It Xr git-mg 1
merge
.It Xr git-ch 1
checkout
.It Xr git-ad 1
add
.It Xr git-cp 1
cherry-pick
.It Xr git-co 1
commit
.It Xr git-rs 1
reset
.It Xr git-rh 1
reset hard
.It Xr git-pu 1
push
.It Xr git-pa 1
push all
.It Xr git-se 1
send-email
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
