.Dd hhvn-git
.Dt hhvn-git 7
.Os
.Sh Name
.Nm hhvn-git
.Nd set of git aliases and wrappers
.Sh FILES
$HOME/.config/git/*
.Sh COMPONENTS
.Xr git-hs 1
- history

.Xr git-fm 1
- format-patch

.Xr git-ac 1
- add & commit

.Xr git-re 1
- remote

.Xr git-mg 1
- merge

.Xr git-ch 1
- checkout

.Xr git-ad 1
- add

.Xr git-cp 1
- cherry-pick

.Xr git-co 1
- commit

.Xr git-rs 1 ,
.Xr git-rh 1 ,
- reset

.Xr git-pu 1 ,
.Xr git-pa 1
- push

.Xr git-se 1
- send-email
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
