.Dd hhvn-git
.Dt hhvn-git 7
.Os
.Sh Name
.Nm hhvn-git
.Nd set of git aliases and wrappers
.Sh FILES
$HOME/.config/git/*
.Sh COMPONENTS
.Xr git-hs 1
- history

.Xr git-fm 1
- format-patch

.Xr git-ac 1
- add & commit

.Xr git-re 1
- remote

.Xr git-mg 1
- merge

.Xr git-ch 1
- checkout

.Xr git-co 1
- commit

.Xr git-pu 1
- push

.Xr git-pa 1
- push all branches
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
