.Dd 27 Apr 2021
.Dt git-re 1
.Os hhvn-git(7)
.Sh Name
.Nm git-re 
.Nd comfy
.Xr git-remote 1
wrapper.
.Sh SYNOPSIS
.Nm git re
.Ar [SUBCOMMAND]
.Ar [GIT-REMOTE-OPTIONS]
.Ar [GIT-REMOTE-ARGUMENTS]
.Sh DESCRIPTION
Display verbose information if no arguments given.

Allow add and set-url to act somewhat interchangably depending on context.

Else, act just like
.Xr git-remote 1 "."
.Sh SEE ALSO
.Xr git-remote 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
