.Dd 27 Apr 2021
.Dt git-fm 1
.Os hhvn-git(7)
.Sh Name
.Nm git-fm 
.Nd add label of current CWD basename to subject of
.Xr git-format-patch 1 "."
.Sh SYNOPSIS
.Nm git fm
.Ar [GIT-FORMAT-PATCH-OPTIONS]
.Ar [GIT-FORMAT-PATCH-ARGUMENTS]
.Sh SEE ALSO
.Xr git-format-patch 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
