.Dd 27 Apr 2021
.Dt git-rs 1
.Os hhvn-git(7)
.Sh Name
.Nm git-rs ,
.Nm git-rh
.Nd alias'
for
.Xr git-reset 1
.Sh SYNOPSIS
.Nm git rs
.Ar [GIT-RESET-OPTIONS]
.Ar [GIT-RESET-ARGUMENTS]
.Nm git rh
.Ar [GIT-RESET-OPTIONS]
.Ar [GIT-RESET-ARGUMENTS]
.Sh DESCRIPTION
.Nm git rh
uses the --hard option by default.
.Sh SEE ALSO
.Xr git-reset 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
