.Dd 05 May 2021
.Dt git-fi 1
.Os hhvn-git(7)
.Sh Name
.Nm git-fi
.Nd calls
.Xr find 1
but only returns files tracked by git.
.Sh SYNOPSIS
.Nm git fi
.Op Fl HL
.Ar path...
.Op Ar operand_expression...
.Sh SEE ALSO
.Bl -item -compact
.It
.Xr git-ls-files 1
.It
.Xr find 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
