.Dd hhvn-git
.Dt git-re 1
.Os
.Sh Name
.Nm git-re 
.Nd comfy
.Xr git-remote 1
wrapper.
.Sh SYNOPSIS
.Nm
.Ar [SUBCOMMAND]
.Ar [GIT-REMOTE-OPTIONS]
.Ar [GIT-REMOTE-ARGUMENTS]
.Sh DESCRIPTION
Display verbose information if no arguments given.

Allow add and set-url to act somewhat interchangably depending on context.

Else, act just like
.Xr git-remote 1 "."
.Sh SEE ALSO
.Xr hhvn-git 7 ","
.Xr git-remote 1 ","
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
