.Dd 27 Apr 2021
.Dt git-ac 1
.Os hhvn-git(7)
.Sh Name
.Nm git-ac 
.Nd combine
.Xr git-add 1
and
.Xr git-commit 1 "."
.Sh SYNOPSIS
.Nm git ac
.Fl m
.Ar message
.Ar [GIT-COMMIT-OPTIONS]
.Nm git ac
.Ar files
.Sh DESCRIPTION
If supplied -m infer files from it.

If not supplied -m, take list of files and begin formatting COMMIT_EDITMSG.
.Sh SEE ALSO
.Bl -item -compact
.It
.Xr git-add 1
.It
.Xr git-commit 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
