.Dd 27 Apr 2021
.Dt git-pu 1
.Os hhvn-git(7)
.Sh Name
.Nm git-pu ,
.Nm git-pa
.Nd alias' for
.Xr git-push 1 "."
.Sh SYNOPSIS
.Nm git pu
.Ar [GIT-PUSH-OPTIONS]
.Ar [GIT-PUSH-ARGUMENTS]
.Nm git pa
.Ar [GIT-PUSH-OPTIONS]
.Ar [GIT-PUSH-ARGUMENTS]
.Sh DESCRIPTION
.Nm git pa
pushes to all remotes.

Uses "server" as default remote.
.Sh SEE ALSO
.Xr git-push 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk .
