#!/bin/bash

setxkbmap -layout us
setxkbmap -option caps:escape

# unicomp endurapro - increase trackpoint sensitivity
[ "$(uname)" = "OpenBSD" ] && device=/dev/wskbd || device="pointer:Unicomp Inc Unicomp 10x Kbrd R7_2_w_PS_R7_38"
xinput set-prop "$device" "Coordinate Transformation Matrix" 4 0 0 0 4 0 0 0 4
xinput set-prop "$device" "libinput Accel Speed" 2
xinput set-prop "$device" "libinput Button Scrolling Button" 3                                                  
xinput set-prop "$device" 'libinput Scroll Method Enabled' 0 0 1
