#!/bin/bash
#
# i3blocks/cal
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

get_cal() {
	calcurse -D $HOME/.config/calcurse $1 | awk "/$2/" | wc -l
}
todo=$(get_cal -t)
if [ "$todo" == "0" ]
then
	todo=$todo
else
	todo=$(($todo-1))
fi
echo "| CAL A:$(get_cal -a "*")/T:$todo"
echo
echo \#236B1B
