#!/bin/bash
#
# i3blocks/disk2
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

sda2=$(df -h | awk '/sda2/ {print $3 "/" $4}')
echo "| SDA2 $sda2"
echo
echo \#3157B5
