#!/bin/bash
#
# i3blocks/host
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 haydenh.gitlab.io/p/gplv2.license

hostget="\u@\h"
echo "< ${hostget@P}"
echo 
echo \#ff003b
