#!/bin/bash
#
# i3blocks/mem
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 ../../.licenses/gplv2.license
#

echo "< M $(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
echo
echo \#009dc1
