#!/bin/bash
#
# i3blocks/net
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 haydenh.gitlab.io/p/gplv2.license

ip=$(curl -s http://icanhazip.com/)
echo "< $ip"
echo
echo \#4Da0C6
