#!/bin/bash
#
# i3blocks/net
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 ../../.licenses/gplv2.license
#

ip=$(curl -s http://icanhazip.com/)
echo "< $ip"
echo
echo \#4DB0C6
