#!/bin/bash
#
# i3blocks/news
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

newsboat -x reload 2>/dev/null
unread=$(newsboat -x print-unread | sed 's/unread articles//g')

echo "[NEWS $unread]"
echo
echo \#498364
