#!/bin/bash
#
# i3blocks/time
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 haydenh.gitlab.io/p/gplv2.license

echo "< $(date +%d/%m)"
echo
echo \#ff7777
