#!/bin/bash
#
# i3blocks/title
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 haydenh.gitlab.io/p/gplv2.license

id=$(xprop -root _NET_ACTIVE_WINDOW | awk '// {print $5}')
out=$(xprop -id $id | awk '/WM_ICON_NAME\(STRING\)/ { $1=""; $2=""; print}' | sed 's/"//g' | sed "s/^[ \t]*//" | cut -zc-40)
echo $out
echo
echo \#226644
