#!/bin/bash
#
# i3blocks/title
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton.

id=$(xprop -root _NET_ACTIVE_WINDOW | awk '// {print $5}')
out1=$(xprop -id $id | awk '/WM_CLASS/ {print $3}' | sed 's/"//g' | sed 's/,//g')
out2=$(xprop -id $id | awk '/_NET_WM_NAME/{ $1=""; $2=""; print}' | sed 's/"//g' | sed "s/^[ \t]*//")
if [ "$BLOCK_BUTTON" == "1" ]
then
	dunstify "Current window title" "$out2"
fi
echo "$out1 - $(echo "$out2" | cut -zc-25)"
echo
echo \#4a6b1b
