#!/bin/bash
#
# i3blocks/weather
# Created by Hayden Hamilton
#
# haydenvh.com
# Copyright (c) 2019 Hayden Hamilton. LICENSE:GPLv2 haydenh.gitlab.io/p/gplv2.license

curl -Ss 'https://wttr.in?0TQ' | cut -c 16- > ~/.cache/weather
echo "< $(sed 2q ~/.cache/weather | sed 's/\.\./ /g' | xargs echo)"
echo
echo \#249980
