#!/bin/sh

[ -z $1 ] && printf "download files from a gopher menu\nusage: gopherdl <uri>\n" && exit

curl $1 | tr -d '\r' | sed "/^\./d;s/^./&	/" | awk -F"	" '$1 != "1" {print "gopher://"$4":"$5"/"$1$3}' | while IFS= read -r uri
do
	fname=$(echo "$uri" | sed 's~gopher://[^/]*~~;s~^/[A-Za-z0-9]/~~')
	dir=$(dirname "$fname")
	[ "$dir" != "" ] && [ "$dir" != "$fname" ] && mkdir -p $dir
	echo "$fname"
	curl "$uri" > $fname
done
