#!/bin/sh

[ -z $1 ] && echo "usage: kshrcremote <[user@]hostname> [other users]" && exit 1
host=$1
shift

for i in 8 9 10 11 12 13 14 15
do
	tput setab $i
	printf '   '
	tput sgr0
	tput setaf $i
	printf '%03d' $i
	tput sgr0
	tput setab $i
	printf '   '
	tput sgr0
	echo
done
printf "Colour? "
read c </dev/tty

rm /tmp/kshrc
cat $HOME/.config/ksh/* | sed -E "s/setaf 5/setaf $c/g;"'s/setaf ([0-9]*)/setaf \1 \1 \1/g' > /tmp/kshrc
scp /tmp/kshrc $host:.profile
for u in $@
do
	ssh -o "ControlMaster=auto" -o "ControlPath=/tmp/kshrcremote.%h.%p.%r.sock" -o "ControlPersist=1m" $host sh -c 'sudo cp $HOME/.profile '"/home/$u/.profile"' && doas cp $HOME/.profile'"/home/$u/.profile"
done
ssh $host
