#!/bin/sh
#
# usage: musictaginteractive [artist] [album]

[ "$1" != "" ] && sartist=1 && artist="$1"
[ "$2" != "" ] && salbum=1 && album="$2"

get(){
	printf "$1? "
	read $1 </dev/tty
}

[ ${sartist:-0} -ne 1 ] && get artist
[ ${salbum:-0} -ne 1 ] && get album

num=0
for f in *
do
	num=$(($num+1))
	echo "$(tput setaf 10)$f:$(tput sgr0)"
	get title
	musictag "$f" "$artist" "$title" "$album" "$(printf "%02d" "$num")"
done
