#!/bin/sh

[ "$1" = "ts" ] && {
	mkdir -p $HOME/general/videos/copy
	youtube-dl --format="(bestvideo[height<=640]+bestaudio)[ext=webm]/bestvideo[height<=640]+bestaudio/best[height<=640]/bestvideo+bestaudio/best" --add-metadata -ic "$2" -o "$HOME/general/videos/copy/%(uploader)s-%(title)s.%(ext)s"
}

[ "$1" != "ts" ] && {
	ts "$0" "ts" "$1"
}
