#!/bin/sh
#
# uptimemon.sh - monitor and record uptime (records)
#
# hayden@hhvn.uk
# Copyright (c) 2020 Hayden Hamilton
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

d=$HOME/net/exec/uptime

#for s in matrix.hhvn.uk hhvn.uk irc1 irc2 dumbterm.hhvn.uk phony.hhvn.uk port.hhvn.uk mx1.hhvn.uk
for s in hhvn.uk irc1 irc2 dumbterm.hhvn.uk phony.hhvn.uk port.hhvn.uk mx1.hhvn.uk neutron.hhvn.uk
do 
	curr=$(ssh $s uptime | grep 'days' | awk '{print $3}' | grep '^[^:]*$' || echo 0)
	ssh $s uptime >/dev/null && down=n || down=y # run the cmd again - variable can't be set
                                                     # in substitions
	[ ! -f $d/$s ] && echo "curr	$curr" > $d/$s
	[ -f $d/$s ] && {
		awk -F"	" -v "curr=${curr:-0}" '
			$1 == "curr" {
				if ($2 > curr) {
					print "curr	" curr
					print "record	" $2
				} else {
					print "curr	" curr
				}
			}
			$1 == "record"' < $d/$s > $d/$s.new 
		mv $d/$s.new $d/$s
		[ "$down" = "y" ] && chmod +x $d/$s || chmod -x $d/$s # use executable perm to
                                                                      # signal to uptime.dcgi
	}
done
