#!/bin/sh

links=$(grep -Eo '[A-Za-z][A-Za-z]*://[^ ]*' < /dev/stdin 2>/dev/null | sed 's/[>,:)]$//')
[ $(echo "$links" | wc -l) -eq 1 ] && link=$links || link=$(printf 'ALL\n%s\n' "$links" | dmenu -i)
[ "$link" = "" ] && exit 1

# hand=$(printf "mpvms video
# mpvms
# mpv --pause
# popupmpv
# youtube-dl --add-metadata -ic
# youtube-dl --add-metadata -xic
# $(xprop -id $(cat /tmp/tabbed.xid) >/dev/null && echo "surf -e $(cat /tmp/tabbed.xid)")
# >/tmp/tabbed.xid tabbed -cr2 surf -e ''
# toxclip
# netimg
# netpdf
# popupcurl
# popupcgo
# popupw3m
# gpgimport
# torsocks mpvms video
# torsocks mpvms
# torsocks mpv --pause
# torsocks popupmpv
# torsocks youtube-dl --add-metadata -ic
# torsocks youtube-dl --add-metadata -xic
# torsocks $(xprop -id $(cat /tmp/tabbed.xid) >/dev/null && echo "surf -e $(cat /tmp/tabbed.xid)")
# torsocks >/tmp/tabbed.xid tabbed -cr2 surf -e ''
# torsocks netimg
# torsocks netpdf
# torsocks popupcurl
# torsocks popupcgo
# torsocks popupw3m
# torsocks gpgimport" | dmenu -i)

# [ "$link" = "ALL" ] && {
# 	for u in $links
# 	do
# 		nohup sh -c "$hand $u" >/dev/null &
# 	done
# } || nohup sh -c "$hand $link" >/dev/null &

[ "$link" = "ALL" ] && {
	plumb $links
} || plumb "$link"
