#!/bin/sh -x
# usage: wbcachemake

cache=$HOME/general/cache/

donorm(){
	[ "$args" = "" ] && {
		convert $file -sparse-color Barycentric '0,0 black 0,%h white' -function polynomial 3.5,-3.2,1.15   /tmp/blurmap.png
		convert $file /tmp/blurmap.png -compose Blur -set option:compose:args 9 -composite $1
	} || {
		convert $file $args $1
	}
	files="$files $1"
}

mkdir -p $cache/wallblur

files=$(find images/wallpapers/ -type f -name "*.png")

for file in $files
do
	[ ! -f $cache/wallblur/$(basename "$file") ] && {
		echo $file start
		donorm "$cache/wallblur/$(basename $file)"
		echo $file done
	}
done
