#!/bin/ksh

alias less="\less -R"
mkcd(){
	mkdir -p $1
	cd $1
}
uncd(){
	cd $OLDPWD
}
irclog(){
	[ -z $1 ] && ls $HOME/.cache/irclogs && return
	[ -f $HOME/.irssi/log2ansi.pl ] && log2ansi=$HOME/.irssi/log2ansi.pl\ --clear
	[ -f $HOME/.config/irssi/log2ansi.pl ] && log2ansi=$HOME/.config/irssi/log2ansi.pl\ --clear
	echo "$1" | grep '/' >/dev/null && dir=$1 || dir=$HOME/.cache/irclogs/$1
	cat $(find $dir | sed -E 's/(..)-(..)-(..)/\3-\2-\1/g' | sort | sed -E 's/(..)-(..)-(..)/\3-\2-\1/g') | ${log2ansi:-cat}| less
}
alias q="exit"
alias duf="duf -style ascii"
alias g="git"
alias vsplit="vim -O"
alias split="vim -o"
alias b="git branch"
alias l="\ls --color=auto -Fh"
alias ls="\ls --color=auto"
alias d="\ls --color=auto -FCash"
alias la="\ls --color=auto -FAh"
alias ll="\ls --color=auto -Flh"
alias lla="\ls --color=auto -FlAh"
alias r="\rm"
alias rr="\rm -rf"
alias v="nvim"
alias c="\clear"
alias f="\find"
alias xi="doas xbps-install"
alias xiu="doas xbps-install -S; doas xbps-install -yu xbps; doas xbps-install -yu; doas xbps-remove -Ooy; rm -rf ~/.cache ~/.mozilla ~/.local/share/webkitgtk ~/.viminfo ~/.wget-hsts ~/.lesshst ~/.sh_history ~/.python_history ~/.*history ~/.*hst* ~/.dbus ~/.w3m ~/.config/vimb/cookies.db; doas vkpurge rm all"
alias xq="doas xbps-query"
alias xr="doas xbps-remove"
alias wget="\wget --hsts-file="/dev/null""
alias pipes="\pipes -R -r 10000 -c 10 -c 11 -c 12 -c 13 -c 14 -c 15 -s 15"
alias clock="tty-clock -s -c -C 7"
alias ytdl="youtube-dl --add-metadata -ic"
alias ytdla="youtube-dl --add-metadata -xic"
alias map="telnet mapscii.me"
alias irssi="\irssi --home ~/.config/irssi/"
alias zsleep="doas zzz"
alias hibernate="doas ZZZ"
alias rmst="bash ~/.scripts/random/gnulinux.sh"
alias vimb="\vimb --no-maximize"
alias mkconfall="mkmailpass; mkalias"
alias make="\make CC=tcc"
alias dmake="doas make CC=tcc"
alias nm="export ESCDELAY=5; neomutt"
alias maic="doas make install clean"
alias homesync="rsync --port 22 --delete -azPe 'ssh -p 222' --exclude=general --exclude=.cache --exclude=.local/cache $HOME/ void@192.168.1.20:/home/void/homedir/"
alias tmux="\tmux -f $HOME/.config/tmux/config"
alias notes="vim ~/.local/notes"
alias fwknop="fwknop --rc-file=$HOME/.config/fwknop/config --save-args-file=/dev/full"
alias edconf="nvim ~/.config/zsh/.zshrc"
alias gnu.matrix="fwknop --rc-file=$HOME/.config/fwknop/config --save-args-file=/dev/full -sn gnu.matrix && ssh gnu.matrix"
alias rss="sfeed_update $XDG_CONFIG_HOME/sfeed/config && . $XDG_CONFIG_HOME/sfeed/config && sfeed_curses $HOME/.local/sfeed/*"
alias diff="colordiff"
alias irc="(sleep 1 && xdotool type 'tmux a' && xdotool key Return) & ssh local"
alias gpg="\gpg --armour"
alias ~d="cd ~/general/downloads; ls"
alias ~do="cd ~/general/documents; ls"
alias ~iw="cd ~/images/wallpapers; ls"
alias ~i="cd ~/images; ls"
alias ~v="cd ~/videos; ls"
alias ~m="cd ~/music; ls"
alias ~w="cd ~/work; ls"
alias ~c="cd ~/.config; ls"
alias ~s="cd ~/.scripts; ls"
alias ~sb="cd ~/.scripts/bin; ls"
alias ~sbdi="cd ~/.scripts/bin/display; ls"
alias ~sbdm="cd ~/.scripts/bin/dmenu; ls"
alias ~sbi="cd ~/.scripts/bin/i3; ls"
alias ~sbm="cd ~/.scripts/bin/misc; ls"
alias ~="cd"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."
alias ............="cd ../../../../../../../../../../.."
alias bbs="printf '\n%s\n%s\n' 'hhvn' \"$(dpass bbs.hlirc.net)\" | cat - /dev/tty | nc bbs.hlirc.net 23"
alias camerasync="rsync -azP /mnt/DCIM/* ~/general/images/byme"
matrix(){
	ssh matrix & >/dev/null
	sleep 0.5
	xdotool type ./gomuks; xdotool key Return
}
