#!/bin/ksh

[ -z $ENV ] && export ENV=$HOME/.profile

seteditor(){
	command -v $1 >/dev/null && export EDITOR=$1
	set vi
}


seteditor vi
seteditor vis
seteditor vim
seteditor nvim

settitle(){
	# set terminal's title
	printf "\033]0;%s\007" "$@"
}

PS1="\$(__ksh_prompt \$?)\$(settitle ksh)"
PS2="$(tput setaf 7):; $(tput sgr0)" 
PS3="$(tput setaf 7):; $(tput sgr0)$(tput el) "
PS4="$(tput setaf 7):; $(tput sgr0)" 

export PS1 PS2 PS3 PS4

export PATH="$PATH:$HOME/.scripts/bin"
for f in $HOME/.config/ksh/*
do
	[ "$(basename "$f")" != "kshrc" ] && . $f
done
