#!/bin/ksh

[ -z $ENV ] && export ENV=$HOME/.profile

seteditor(){
	command -v $1 >/dev/null && export EDITOR=$1
	set vi
}


seteditor vi
seteditor vis
seteditor vim
seteditor nvim

settitle(){
	# set terminal's title
	printf "\033]0;%s\007" "$1"
}

_ksh_prompt(){
	errorcode=$1
	tput setaf 10
	[ $errorcode -eq 0 ] && tput setaf 15 || tput setaf 10
	printf "%s " $errorcode
	tput setaf 5
	printf "%s " $(whoami)
	tput setaf 3
	printf "%s" $(git branch 2>/dev/null | grep '^*' | awk '{print $2 "|"}')
	git diff 1>/dev/null 2>/dev/null && {
		git diff | grep '.' >/dev/null && tput setaf 8 || tput setaf 15
		printf "%s " $(git diff 2>/dev/null | grep -E '^(\+\+\+|---)' | sed -E 's~^[^a]*a/|^[^b]*b/~~' \
			| grep -v /dev/null | uniq | wc -l | tr -d '\n' | grep '.' || printf 0)
	}
	tput setaf 7
	printf "%s " $(pwd | sed "s-$HOME-~-")
	tput setaf 7
	printf "$ "
	tput sgr0
}
PS1="\$(_ksh_prompt \$?)"
PS2="$(tput setaf 7):; $(tput sgr0)" 
PS3="$(tput setaf 7):; $(tput sgr0)$(tput el) "
PS4="$(tput setaf 7):; $(tput sgr0)" 

export PS1 PS2 PS3 PS4

for f in $HOME/.config/ksh/*
do
	[ "$(basename "$f")" != "kshrc" ] && . $f
done
