#!/bin/ksh

export LESS_TERMCAP_mb=$(printf '\033[1;31m')
export LESS_TERMCAP_md=$(printf '\033[1;35m')
export LESS_TERMCAP_me=$(printf '\033[0m')
export LESS_TERMCAP_so=$(printf '\033[92m')
export LESS_TERMCAP_se=$(printf '\033[0m')
export LESS_TERMCAP_us=$(printf '\033[1;32m')
export LESS_TERMCAP_ue=$(printf '\033[0m')
