#!/bin/ksh

# Fuck GNU
# For some reason I can't get grep to ignore "binary" files with POSIXLY_CORRECT
grep --version 2>/dev/null | grep 'GNU' >/dev/null && __ksh_prompt_gnu_binary="a"

# use \[..\] to prevent counting
__prompt_col(){
	printf '\[%s\]' "$(tput setaf $1)"
}

__prompt_strip(){
	echo "$0" | grep -v ksh >/dev/null && {
		sed 's/\\\[//g;s/\\\]//g'
	} || cat
}

__ksh_prompt(){
	__prompt_col 14
	printf "\[%%%$(echo "$(tput cols) - 1" | bc)s\r\]"

	__ksh_prompt_errorcode=$1
	# tput setaf 10 >/dev/null
	[ $__ksh_prompt_errorcode -eq 0 ] && __prompt_col 15 || __prompt_col 10
	printf '%s ' "$__ksh_prompt_errorcode"
	__prompt_col 5
	printf "%s " "$(whoami)"
	[ "$_PROMPT_GIT" = "y" ] && {
		__prompt_col 3
		printf "%s" $(git branch 2>/dev/null | grep '^*' | awk '{print $2 "|"}')
		__ksh_prompt_diff=$(git diff 2>/dev/null)
		[ $? -eq 0 ] && {
			echo "$__ksh_prompt_diff" | grep '.' >/dev/null && __prompt_col 8 || __prompt_col 15
			printf "%s+" $(echo "$__ksh_prompt_diff" 2>/dev/null | grep -${__ksh_prompt_gnu_binary}E '^(\+\+\+|---)' | sed -E 's~^[^a]*a/|^[^b]*b/~~' \
				| grep -v /dev/null | uniq | wc -l | tr -d '\n' | grep '.' || printf 0)
			__ksh_prompt_log=$(git log --pretty=format:"commit %h%d")
			printf '%s\n' "$__ksh_prompt_log2" | head -n 1 | grep -v '.*\/.*' >/dev/null && __prompt_col 14 && {
				printf '%s\n' "$__ksh_prompt_log" | awk -v "c=0" '
					/^commit/ {
						if ($0 ~ /\//) {
							printf("%d", c)
							exit
						} else c += 1
					}'
				printf '^'
			}
			printf ' '
		}
	}
	__prompt_col 7
	printf "%s " "$(pwd | sed "s-$HOME-~-")"
	echo "$0" | grep -v ksh >/dev/null && {
		printf "($(basename $0))"
	}
	printf "$\[ \]" # uncount an additional char
	printf '\[%s\]' "$(tput sgr0)"
}

export _PROMPT_GIT=y
alias hide_git="export _PROMPT_GIT=n"
alias show_git="export _PROMPT_GIT=y"
